version: '3'
services:
  nodejs:
    image: docker-node-express-mongoapp
    build: web-site
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
   